---
# General prereqisites for the application

- name: Install required packages
  apt: pkg={{ item }} state=installed
  with_items:
    - git
    - git-core
    - curl
    - zlib1g-dev
    - libssl-dev
    - libreadline-dev
    - libyaml-dev
    - libsqlite3-dev
    - sqlite3
    - libxml2-dev
    - libxslt1-dev
    - libcurl4-openssl-dev
    - python-software-properties
    - libpq-dev
